name: Pylint Score Report

on:
  push:
    branches:
      - main
      - dev

jobs:
  pylint-score:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Run Image
      run: |
        # Build and start the container. Modify this command according to your setup.
        {{cookiecutter.pre_build_command}}
        docker compose -f {{cookiecutter.compose_file}} build {{cookiecutter.docker_image_name}}

    - name: Execute Pylint
      run: |
        # Execute pylint inside the docker image and extract the score
        SCORE=$(docker compose -f {{cookiecutter.compose_file}} run {{cookiecutter.docker_image_name}} pylint {{cookiecutter.module_path}}| grep 'Your code has been rated at' | awk '{print $7}' | cut -d'/' -f1)
        echo "PYLINT_SCORE=$SCORE" >> $GITHUB_ENV

    - name: Update PyLint Score in README
      run: |
        sed -i "s/Pylint%20Score-[0-9]*\.[0-9]*%2F10/Pylint%20Score-$PYLINT_SCORE%2F10/" README.md
        # Determine badge color based on the score
        if (( $(echo "$PYLINT_SCORE >= 7" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$PYLINT_SCORE >= 5" | bc -l) )); then
          COLOR="yellow"
        else
          COLOR="red"
        fi

        # Replace the badge in README.md
        # sed -i "s|badge/Pylint%20Score-[0-9]*\.[0-9]*%2F10-.*|badge/Pylint%20Score-$SCORE%2F10-$COLOR|" README.md
        sed -i "s|!\[Pylint Score\].*|![Pylint Score](https://img.shields.io/badge/Pylint%20Score-$PYLINT_SCORE%2F10-$COLOR)|g" README.md
        git config user.email action@github.com
        git config user.name gitHub-action
        git add README.md
        git commit -m "Update PyLint Score" || echo "No changes to commit"
        git push